### ISSUE TITLE
netstandard 2.0 build depends on Microsoft.Bcl.Memory causing conflict with Indexes provided by IndexRange

### ISSUE THREAD

**Issue by 2PintChristianN** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#3099]
**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel.Tokens 8.3.1

**Where is the issue?**
Microsoft.IdentityModel.Tokens 8.3.1 netstandard 2.0 build Depends on Microsoft.Bcl.Memory

**Is this a new or an existing app?**
Existing app, Api .Net 4.7.2, working fine with Microsoft.IdentityModel.Tokens 8.3.0

**Repro**
Using IndexRange to provide support for language features of index, especially
```c#
var aList = someArray.ToList();
string last = actions[^1];  // <<<<<
```
Also see https://github.com/bgrainger/IndexRange/issues/14

**Expected behavior**
Everything compiling without issues, and no major change since it is only a minor version change. (trying to be optimistic at times)
(Also wouldn't expect Microsoft.Bcl.Memory to break IndexRange usage, but that might be a more difficult issue to resolve.)
Change of package use would be nice to have in release notes with explanation.
Introduced in #2817

**Actual behavior**
Compile time errors
```
CS0656 Missing compiler required member 'System.Index..ctor'
CS0518 Predefined type 'System.Index' is not defined or imported
CS0518 Predefined type 'System.Range' is not defined or imported
```

**Possible solution**
Is `Microsoft.Bcl.Memory` required as a dependency in `netstandard` builds?
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/658604a398105c95fb229601ea3a91849cc6a145/src/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.csproj#L68
 `<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">`

**Current workaround**
Block version 8.3.1 and later

**Comment by mykolav** [comment]
For anyone else who lands on this issue.

Running into the same problem, and `csc` gives a seriously misleading error message. It reads:

> Error CS0518: Predefined type 'System.Index' is not defined or imported

But what's really going on is pretty much the opposite -- it should actually say:

> Error CS0433: The type 'Index' exists in both 'IndexRange, Version=1.0.3.0, Culture=neutral, PublicKeyToken=35e6a3c4212514c6' and 'Microsoft.Bcl.Memory, Version=9.0.0.3, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

This is easy to confirm by adding a line of code that explicitly creates an instance of `System.Index` or `System.Range` (instead of relying on the hat `^` or `..` syntax), e.g.: `_ = new System.Index();`
